# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('event_people', models.CharField(blank=True, max_length=100, null=True)),
                ('event_private_yesno', models.NullBooleanField()),
                ('event_description', models.CharField(blank=True, max_length=500, null=True)),
                ('event_immediate_response_yesno', models.NullBooleanField()),
                ('event_reaction', models.CharField(blank=True, max_length=500, null=True)),
                ('event_category', models.CharField(blank=True, choices=[(1, b'exclusion'), (2, b'harassment'), (3, b'stereotyping')], max_length=100, null=True)),
                ('event_cost_rating', models.IntegerField(blank=True, null=True)),
                ('event_cost_desc', models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=100, null=True)),
                ('event_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkplaceSexismTracker.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
