# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceSexismTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_cost_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cost_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkplaceSexismTracker.User'),
        ),
    ]
